[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Ingenieros JR"
authors = [{name = "Gagis", email = "raulantonioguerreroc@gmail.com"}]
dynamic = ["version", "description"]
